# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
redcarpet:
  extensions: [autolink]
url: http://nguquen.github.io


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ngủ Quên

description: Dớt ờ nớ đờ bờ lốc
author:
  name: Ngủ Quên
  github: nguquen
  twitter: quenngu
  bio: Ngày sau sỏi đá cũng cần có nhau...
  email_md5: ebdd75eefbfe7708d5ac1d025c4abc57

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
